name: shop_app
description: A beautiful and animated Flutter app for the shop backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  animate_do: ^3.3.4
  flutter_spinkit: ^5.2.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Vazir
      fonts:
        - asset: fonts/Vazirmatn.ttf
  assets:
    - assets/images/